version: "3.9"

services:

  db:
    image: mysql:8.4
    container_name: gestion-clientes-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: clientes_db
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql


  backend:
    build:
      context: ./backend
    container_name: gestion-clientes-backend
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: rootpass
      DB_NAME: clientes_db
      JWT_SECRET_KEY: Cambia_Esto
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend/clientes-app
      dockerfile: Dockerfile
    container_name: gestion-clientes-frontend
    depends_on:
      - backend
    ports:
      - "4200:4200"

volumes:
  mysql_data:
